# Analiza eksploracyjna danych 
## Część 1: podstawowe informacje o zbiorze, braki danych, wartości zmiennych

Zbiór danych podchodzi z **Kaggle** (`fedesoriano/stroke-prediction-dataset`). 
Przy jego pomocy mozna modelować ryzyko udaru mózgu dla pacjenta o konkretnych parametrach.

Zaczniemy początkowo od podstawowych informacjach o zbiorze - kolumny, braki danych, rodzaje zmiennych etc.

In [2]:
from pathlib import Path
import pandas as pd

In [3]:
data_path = Path("../data/raw/healthcare-dataset-stroke-data.csv")

In [4]:
df = pd.read_csv(data_path)
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

### Podstawowe informacje o zbiorze

Kolumny:

In [29]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

Mamy 5110 obserwacji, przy 12 zmiennych.

In [30]:
df.shape

(5110, 12)

Braki danych.

In [5]:
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

Tylko w BMI - 201 braków.

In [9]:
df.nunique()

id                   5110
gender                  3
age                   104
hypertension            2
heart_disease           2
ever_married            2
work_type               5
Residence_type          2
avg_glucose_level    3979
bmi                   418
smoking_status          4
stroke                  2
dtype: int64

In [31]:
df.duplicated().sum()

0

`id` - unikalny identyfikator pacjenta, brak duplikatów w bazie, nie niesie zadnej wartosci do dalszej predykcji. W dalszej części notatnika przyjrzymy się 
kazdej cesze z osobna.

### Gender

In [32]:
df['gender'].value_counts()

gender
Female    2994
Male      2115
Other        1
Name: count, dtype: int64

In [33]:
df[df['gender'] == 'Other']

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
3116,56156,Other,26.0,0,0,No,Private,Rural,143.33,22.4,formerly smoked,0

In [34]:
df['gender'].value_counts(normalize=True)

gender
Female    0.585910
Male      0.413894
Other     0.000196
Name: proportion, dtype: float64

Zbiór jest względnie zbilansowany pod względem udziału kobiet i męzczyzn, co ciekawe w przeciwieństwie do populacji osob z udarem mozgu w zbiorze danych występuje więcej kobiet niz męzczyzn.

In [38]:
df[['stroke', 'gender']].value_counts()

stroke  gender
0       Female    2853
        Male      2007
1       Female     141
        Male       108
0       Other        1
Name: count, dtype: int64

Tak samo w przypadku osób, u których wystąpił udar.

###